const ADMIN_NAVIGATION_ITEMS = {
    DASHBOARD: 'DASHBOARD',
    PLAYERS: 'PLAYERS',
    TEAMS: 'TEAMS',
    SCHEDULES: 'SCHEDULES',
}

const ADMIN_REQUEST_STATUS = {
    IDLE: 'IDLE',
    IN_PROGRESS: 'IN_PROGRESS',
}

export {
    ADMIN_NAVIGATION_ITEMS,
    ADMIN_REQUEST_STATUS
}